// Punk Queen — ürün listesi. Bu dosyayı YONETIM.html ile güncelleyin.
// Son güncelleme: 07.09.2026 11:49:11
const URUNLER = [
  {"img":"PQ-10149_1.jpg","code":"PQ-10149","type":"COAT","cat":["CARDIGAN"],"price":"68 $","on":true,"color":"GREEN"},
  {"img":"PQ-10149_2.jpg","code":"PQ-10149","type":"COAT","cat":["CARDIGAN"],"price":"68 $","on":true,"color":"BLACK"},
  {"img":"PQ-10149_3.jpg","code":"PQ-10149","type":"COAT","cat":["CARDIGAN"],"price":"68 $","on":true,"color":"WHITE"},
  {"img":"PQ-1073_1.jpg","code":"PQ-1073","type":"CARDIGAN","cat":["CARDIGAN"],"price":"30 $","on":true,"color":"BLUE"},
  {"img":"PQ-1073_2.jpg","code":"PQ-1073","type":"CARDIGAN","cat":["CARDIGAN"],"price":"30 $","on":true,"color":"GRAY"},
  {"img":"PQ-1185_1.jpg","code":"PQ-1185","type":"CARDIGAN","cat":["CARDIGAN"],"price":"25 $","on":true,"color":"GRAY"},
  {"img":"PQ-1185_2.jpg","code":"PQ-1185","type":"CARDIGAN","cat":["CARDIGAN"],"price":"25 $","on":true,"color":"BLACK"},
  {"img":"PQ-1288_1.jpg","code":"PQ-1288","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"GREEN"},
  {"img":"PQ-1288_2.jpg","code":"PQ-1288","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"GRAY"},
  {"img":"PQ-1289.jpg","code":"PQ-1289","type":"CARDIGAN","cat":["CARDIGAN"],"price":"28 $","on":true,"color":"BLACK"},
  {"img":"PQ-1291_2.jpg","code":"PQ-1291","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"WHITE"},
  {"img":"PQ-1292_1.jpg","code":"PQ-1292","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"WHITE"},
  {"img":"PQ-1293.jpg","code":"PQ-1293","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"24 $","on":true,"color":"BLACK"},
  {"img":"PQ-1297_2.jpg","code":"PQ-1297","type":"PANTS","cat":["PANTS"],"price":"15 $","on":true,"color":"WHITE"},
  {"img":"PQ-1298.jpg","code":"PQ-1298","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"26 $","on":true,"color":"BLACK"},
  {"img":"PQ-1299_1.jpg","code":"PQ-1299","type":"DRESS","cat":["DRESS"],"price":"21 $","on":true,"color":"WHITE"},
  {"img":"PQ-1299_2.jpg","code":"PQ-1299","type":"DRESS","cat":["DRESS"],"price":"21 $","on":true,"color":"BLACK"},
  {"img":"PQ-1306_1.jpg","code":"PQ-1306","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BROWN"},
  {"img":"PQ-1306_2.jpg","code":"PQ-1306","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-1307.jpg","code":"PQ-1307","type":"COAT","cat":["CARDIGAN"],"price":"30 $","on":true,"color":"GRAY"},
  {"img":"PQ-1309.jpg","code":"PQ-1309","type":"LEGGINGS","cat":["PANTS"],"price":"18 $","on":true,"color":"BROWN"},
  {"img":"PQ-1310_1.jpg","code":"PQ-1310","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"BLACK"},
  {"img":"PQ-1310_2.jpg","code":"PQ-1310","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"WHITE"},
  {"img":"PQ-1313_1.jpg","code":"PQ-1313","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"ORANGE"},
  {"img":"PQ-1313_2.jpg","code":"PQ-1313","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"WHITE"},
  {"img":"PQ-1313_3.jpg","code":"PQ-1313","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"BLACK"},
  {"img":"PQ-217_1.jpg","code":"PQ-217","type":"CARDIGAN","cat":["CARDIGAN"],"price":"28 $","on":true,"color":"GREEN"},
  {"img":"PQ-217_2.jpg","code":"PQ-217","type":"CARDIGAN","cat":["CARDIGAN"],"price":"28 $","on":true,"color":"NAVY"},
  {"img":"PQ-2200_1.jpg","code":"PQ-2200","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-2200_2.jpg","code":"PQ-2200","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"WHITE"},
  {"img":"PQ-463_1.jpg","code":"PQ-463","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"15 $","on":true,"color":"BORDO"},
  {"img":"PQ-463_2.jpg","code":"PQ-463","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"15 $","on":true,"color":"WHITE"},
  {"img":"PQ-465_1.jpg","code":"PQ-465","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"BLACK"},
  {"img":"PQ-466_1.jpg","code":"PQ-466","type":"CARDIGAN","cat":["CARDIGAN"],"price":"23 $","on":true,"color":"GRAY"},
  {"img":"PQ-466_2.jpg","code":"PQ-466","type":"CARDIGAN","cat":["CARDIGAN"],"price":"23 $","on":true,"color":"BLACK"},
  {"img":"PQ-467_1.jpg","code":"PQ-467","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"GRAY"},
  {"img":"PQ-467_2.jpg","code":"PQ-467","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-470_1.jpg","code":"PQ-470","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"14 $","on":true,"color":"YELLOW"},
  {"img":"PQ-470_2.jpg","code":"PQ-470","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"14 $","on":true,"color":"BLACK"},
  {"img":"PQ-471_1.jpg","code":"PQ-471","type":"CARDIGAN","cat":["CARDIGAN"],"price":"24 $","on":true,"color":"GRAY"},
  {"img":"PQ-471_2.jpg","code":"PQ-471","type":"CARDIGAN","cat":["CARDIGAN"],"price":"24 $","on":true,"color":"BLACK"},
  {"img":"PQ-472_1.jpg","code":"PQ-472","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"WHITE"},
  {"img":"PQ-475.jpg","code":"PQ-475","type":"CARDIGAN","cat":["CARDIGAN"],"price":"23 $","on":true,"color":"BLACK"},
  {"img":"PQ-5009.jpg","code":"PQ-5009","type":"VEST","cat":["CARDIGAN"],"price":"45 $","on":true,"color":"GREEN"},
  {"img":"PQ-5201.jpg","code":"PQ-5201","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"28 $","on":true,"color":"BLACK"},
  {"img":"PQ-5203_1.jpg","code":"PQ-5203","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"26 $","on":true,"color":"WHITE"},
  {"img":"PQ-5203_2.jpg","code":"PQ-5203","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"26 $","on":true,"color":"BLACK"},
  {"img":"PQ-5205.jpg","code":"PQ-5205","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"27 $","on":true,"color":"WHITE"},
  {"img":"PQ-5206_1.jpg","code":"PQ-5206","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"WHITE"},
  {"img":"PQ-5206_2.jpg","code":"PQ-5206","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"BLACK"},
  {"img":"PQ-5208_1.jpg","code":"PQ-5208","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-5208_2.jpg","code":"PQ-5208","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"WHITE"},
  {"img":"PQ-5211-5212.jpg","code":"PQ-5211 + PQ-5212","type":"TAKIM","cat":["SWEATSHIRT","TRACKSUIT","PANTS"],"price":"16 $ + 14 $","on":true,"color":"BLACK","variants":{"SWEATSHIRT":{"code":"PQ-5211","price":"16 $"},"PANTS":{"code":"PQ-5212","price":"14 $"},"TRACKSUIT":{"code":"PQ-5211 + PQ-5212","price":"16 $ + 14 $"}}},
  {"img":"PQ-5213_1.jpg","code":"PQ-5213","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"BLACK"},
  {"img":"PQ-5213_2.jpg","code":"PQ-5213","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"WHITE"},
  {"img":"PQ-5215_2.jpg","code":"PQ-5215","type":"PANTS","cat":["PANTS"],"price":"15 $","on":true,"color":"WHITE"},
  {"img":"PQ-5218_1.jpg","code":"PQ-5218","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"WHITE"},
  {"img":"PQ-5218_2.jpg","code":"PQ-5218","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"BLACK"},
  {"img":"PQ-5221.jpg","code":"PQ-5221","type":"DRESS","cat":["DRESS"],"price":"24 $","on":true,"color":"BLACK"},
  {"img":"PQ-5222.jpg","code":"PQ-5222","type":"DRESS","cat":["DRESS"],"price":"24 $","on":true,"color":"BLACK"},
  {"img":"PQ-5224_1.jpg","code":"PQ-5224","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"GRAY"},
  {"img":"PQ-5224_2.jpg","code":"PQ-5224","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"BEIGE"},
  {"img":"PQ-5231.jpg","code":"PQ-5231","type":"TRACKSUIT","cat":["TRACKSUIT"],"price":"24 $","on":true,"color":"BLACK"},
  {"img":"PQ-5233_1.jpg","code":"PQ-5233","type":"CARDIGAN","cat":["CARDIGAN"],"price":"35 $","on":true,"color":"BLACK"},
  {"img":"PQ-5233_2.jpg","code":"PQ-5233","type":"CARDIGAN","cat":["CARDIGAN"],"price":"35 $","on":true,"color":"GRAY"},
  {"img":"PQ-5236.jpg","code":"PQ-5236","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"GRAY"},
  {"img":"PQ-5237_1.jpg","code":"PQ-5237","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"WHITE"},
  {"img":"PQ-5237_3.jpg","code":"PQ-5237","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-5239.jpg","code":"PQ-5239","type":"DRESS","cat":["DRESS"],"price":"20 $","on":true,"color":"BLACK"},
  {"img":"PQ-5244_1.jpg","code":"PQ-5244","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"WHITE"},
  {"img":"PQ-5244_2.jpg","code":"PQ-5244","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-5245.jpg","code":"PQ-5245","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"BLACK"},
  {"img":"PQ-6200_1.jpg","code":"PQ-6200","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"BLACK"},
  {"img":"PQ-6200_2.jpg","code":"PQ-6200","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"WHITE"},
  {"img":"PQ-6201.jpg","code":"PQ-6201","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"20 $","on":true,"color":"WHITE"},
  {"img":"PQ-6202.jpg","code":"PQ-6202","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-6204-6203_1.jpg","code":"PQ-6204 + PQ-6203","type":"TAKIM","cat":["SWEATSHIRT","TRACKSUIT","PANTS"],"price":"17 $ + 15 $","on":true,"color":"WHITE","variants":{"SWEATSHIRT":{"code":"PQ-6204","price":"17 $"},"PANTS":{"code":"PQ-6203","price":"15 $"},"TRACKSUIT":{"code":"PQ-6204 + PQ-6203","price":"17 $ + 15 $"}}},
  {"img":"PQ-6204-6203_2.jpg","code":"PQ-6204 + PQ-6203","type":"TAKIM","cat":["SWEATSHIRT","TRACKSUIT","PANTS"],"price":"17 $ + 15 $","on":true,"color":"BLACK","variants":{"SWEATSHIRT":{"code":"PQ-6204","price":"17 $"},"PANTS":{"code":"PQ-6203","price":"15 $"},"TRACKSUIT":{"code":"PQ-6204 + PQ-6203","price":"17 $ + 15 $"}}},
  {"img":"PQ-6205.jpg","code":"PQ-6205","type":"PANTS","cat":["PANTS"],"price":"19 $","on":true,"color":"WHITE"},
  {"img":"PQ-6207.jpg","code":"PQ-6207","type":"KNITTED SWEATER","cat":["SWEATSHIRT"],"price":"20 $","on":true,"color":"BLACK"},
  {"img":"PQ-6208_1.jpg","code":"PQ-6208","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"21 $","on":true,"color":"WHITE"},
  {"img":"PQ-6209.jpg","code":"PQ-6209","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"17 $","on":true,"color":"BLACK"},
  {"img":"PQ-6210.jpg","code":"PQ-6210","type":"CARDIGAN","cat":["CARDIGAN"],"price":"30 $","on":true,"color":"WHITE"},
  {"img":"PQ-6212_1.jpg","code":"PQ-6212","type":"PANTS","cat":["PANTS"],"price":"13 $","on":true,"color":"WHITE"},
  {"img":"PQ-6212_2.jpg","code":"PQ-6212","type":"PANTS","cat":["PANTS"],"price":"13 $","on":true,"color":"GRAY"},
  {"img":"PQ-6213.jpg","code":"PQ-6213","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"19 $","on":true,"color":"WHITE"},
  {"img":"PQ-6214_1.jpg","code":"PQ-6214","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"18 $","on":true,"color":"WHITE"},
  {"img":"PQ-7006_1.jpg","code":"PQ-7006","type":"DRESS","cat":["DRESS"],"price":"23 $","on":true,"color":"BLACK"},
  {"img":"PQ-7006_2.jpg","code":"PQ-7006","type":"DRESS","cat":["DRESS"],"price":"23 $","on":true,"color":"NAVY"},
  {"img":"PQ-7014.jpg","code":"PQ-7014","type":"PANTS","cat":["PANTS"],"price":"16 $","on":true,"color":"BLACK"},
  {"img":"PQ-7015.jpg","code":"PQ-7015","type":"CARDIGAN","cat":["CARDIGAN"],"price":"27 $","on":true,"color":"BLACK"},
  {"img":"PQ-7026_1.jpg","code":"PQ-7026","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"WHITE"},
  {"img":"PQ-7026_2.jpg","code":"PQ-7026","type":"SWEATSHIRT","cat":["SWEATSHIRT"],"price":"16 $","on":true,"color":"BLACK"},
  {"img":"PQ-7235-7236.jpg","code":"PQ-7235 + PQ-7236","type":"TAKIM","cat":["CARDIGAN","TRACKSUIT","PANTS"],"price":"29 $ + 17 $","on":true,"color":"BLACK","variants":{"CARDIGAN":{"code":"PQ-7235","price":"29 $"},"PANTS":{"code":"PQ-7236","price":"17 $"},"TRACKSUIT":{"code":"PQ-7235 + PQ-7236","price":"29 $ + 17 $"}}},
  {"img":"PQ-7238-7237.jpg","code":"PQ-7238 + PQ-7237","type":"TAKIM","cat":["SWEATSHIRT","TRACKSUIT","PANTS"],"price":"13 $ + 13 $","on":true,"color":"BLACK","variants":{"SWEATSHIRT":{"code":"PQ-7238","price":"13 $"},"PANTS":{"code":"PQ-7237","price":"13 $"},"TRACKSUIT":{"code":"PQ-7238 + PQ-7237","price":"13 $ + 13 $"}}},
  {"img":"PQ-7239_1.jpg","code":"PQ-7239","type":"SUIT","cat":["TRACKSUIT"],"price":"37 $","on":true,"color":"BLACK"},
  {"img":"PQ-7239_2.jpg","code":"PQ-7239","type":"SUIT","cat":["TRACKSUIT"],"price":"37 $","on":true,"color":"GRAY"},
  {"img":"PQ-7239_3.jpg","code":"PQ-7239","type":"SUIT","cat":["TRACKSUIT"],"price":"37 $","on":true,"color":"BORDO"},
];
